version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: clipcraft-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/.clipcraft-data:/app/.clipcraft-data
    ports:
      - '3000:3000'
